"""empty message

Revision ID: d030a1816b46
Revises: 611af994b659
Create Date: 2021-03-02 16:04:31.722213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd030a1816b46'
down_revision = '611af994b659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('last_clicked_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'last_clicked_on')
    # ### end Alembic commands ###
